### ISSUE TITLE
Error when running in PWD environment

### ISSUE THREAD

**Issue by willopez** [shyim/shopware#15]
I clicked the button to load this image in the PWD environment and looked at the logs of the Shopware image and see the following error: 

![image](https://user-images.githubusercontent.com/486340/106230300-c611e080-61b4-11eb-88b0-812d36412564.png)

It seems that there is an issue with the initialization of the database(the migrations don't run perhaps?) when the image is being built. If I log into the container and execute `bin/console system:install --create-database --basic-setup` after deleting the install lock.

And then generating the jwt secret(`bin/console system:generate-jwt-secret` everything runs fine

Wondering how this could be fixed in the image? so that the initial run works out of the box.

**Comment by dfsoeten** [comment]
This is the same issue that I'm facing in my current, somewhat custom, containerised Shopware 6 setup. The problem here is that you'd need to create a dependency between a process responsible for migrating the database and the database being ready to accept connections. One way to do this is to create a worker service using something like [wait for it](https://github.com/vishnubob/wait-for-it) to execute `bin/console system:install --create-database --basic-setup --force` after the database is ready.

**Comment by willopez** [comment]
@dfsoeten Thanks for the tip! That would be a good solution for, have you implemented something like it? also, somewhat related to this, do you know what is the purpose of the `docker-compose-advanced.yml`? is that what should be used for an actual production deployment?

**Comment by dfsoeten** [comment]
I'm not sure what the exact intention of this repository is and how it differs from the Docker setup that comes with the [Shopware 6 production repository](https://github.com/shopware/production) (see the [Dockerfile](https://github.com/shopware/production/blob/6.3/Dockerfile) and [Docker Compose](https://github.com/shopware/production/blob/6.3/docker-compose.yml) file), so I'm not in a position to answer your question.  However, I'm currently in the process of deploying a Shopware 6 instance to GCP. And what I found is that you need the Shopware 6 production repository if your intention is to use it in production. See [this](https://www.p16r.nl/2020-08-28-shopware-6-development-versus-production-template/) blog.

Furthermore, I don't have a concrete implementation for you regarding Shopware 6. I do, however, have an implementation for an unrelated PHP/SQL project which might be helpful. I made a few changes so it should look something like this:

Create a file named `mysql-migration.entrypoint.sh`:
```
#!/bin/bash

if [[ ! -f vendor/autoload.php ]]; then
    exit 1;
else
    ./scripts/docker/wait-for-it.sh mysql:3306 -- ./bin/console system:install --create-database --force;
fi
```

Add a service responsible for seeding the database:
```
maintenance:
    image: shyim/shopware:latest
    depends_on:
      - mysql
    env_file:
      - .env
    entrypoint: ['./mysql-migration.entrypoint.sh']
    volumes:
      - state:/state
      - plugins:/var/www/html/custom/plugins
      - files:/var/www/html/files
      - jwt:/var/www/html/config/jwt
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - bundles:/var/www/html/public/bundles
      - sitemap:/var/www/html/public/sitemap
```
