### ISSUE TITLE
Install failed with MySQL v8

### ISSUE THREAD

**Issue by KennyDizi** [shyim/shopware#58]
I'm trying to install MySQL v8 but I saw some errors, bellow is my docker-compose file
```
version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
  shopware:
    image: shyim/shopware:6.4.18.0-php8.1.13
    environment:
      APP_SECRET: wjMHHxmts4ah1fTquytZJQbB6onGrCE3V7Ti45FkZXVkGoZzR57w1cZ75WZ6xqFp
      INSTANCE_ID: 7chE97XKxKwstQO5Xlyg5Zek3DPDImqZhWkKMcAL9GJg7noB
      APP_URL: http://localhost
      DATABASE_HOST: mysql
      DATABASE_URL: mysql://shopware:shopware@mysql:3306/shopware
      INSTALL_LOCALE: vi-VN
      INSTALL_CURRENCY: VND
    ports:
      - 80:80
```
