### ISSUE TITLE
Question, how to initialize the database? 

### ISSUE THREAD

**Issue by thomasbeauvais** [shyim/shopware#6]
Starting up and connected to a fresh database results in this error.

`Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75 Stack trace: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(75): PDO->query(' SEL...') #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(909): Doctrine\DBAL\Driver\PDOConnection->query(' SEL...') #2 /var/www/html/vendor/shopware/core/Framework/Plugin/KernelPluginLoader/DbalKernelPluginLoader.php(36): Doctrine\DBAL\Connection->executeQuery(' SEL...') #3 /var/www/html/vendor/shopware/core/Framework/Plugin/KernelPluginLoader/KernelPluginLoader.php(107): Shopware\Core\Framework\Plugin\KernelPluginLoader\DbalKernelPluginLoader->loadPluginInfos() #4 /var/www/html/vendor/shopware/core/Kernel.php(133): Shopware\Core\Framework\Plugin\KernelPluginLoader\KernelPluginLoader->initializePlugins('/var/www/html') #5 /var/www/html/vendor/shopware in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 42`

**Comment by shyim** [comment]
How did you run the container?

**Comment by thomasbeauvais** [comment]
I just modified the `docker-compose.yml` provided in the README 
```
version: "3.8"
services:
  shopware:
    image: shyim/shopware:latest
    container_name: shopware
    environment:
      APP_SECRET: 440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      INSTANCE_ID: 10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      APP_URL: http://localhost
      DATABASE_HOST: xxx
      DATABASE_URL: xxx
    ports:
      - 80:80
    network_mode: bridge
```

**Comment by shyim** [comment]
Can you show the container logs?

**Comment by thomasbeauvais** [comment]
In an effort to get those logs, I decided to rebuild the container.

It looks like if the container doesn't have the connection exactly when it is built, it doesn't execute the migration.

Thus, I had to remove the container and rebuild it. Now it is building the database. 

Cheers.

**Comment by willopez** [comment]
@thomasbeauvais @shyim I am getting this exact error, I removed the container and re-build, but still, get this error:
```
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75
```

My docker-compose.yml looks like this, the only thing I modified was the ports, I want it bound to port 8080 on the host so that my reverse proxy can run on port 80 and route traffic to shopware.

```
version: "3.8"
services:
  mysql:
    image: bitnami/mysql:5.7
    tmpfs:
      - /var/lib/mysql
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
      MYSQL_DATABASE: shopware
  shopware:
    image: shyim/shopware:latest
    build:
      context: .
    environment:
      APP_SECRET: 440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      INSTANCE_ID: 10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      APP_URL: http://localhost
      MAILER_URL: null://localhost
      DATABASE_HOST: mysql
      DATABASE_URL: mysql://shopware:shopware@mysql:3306/shopware
      SHOPWARE_ES_HOSTS: 
      SHOPWARE_ES_ENABLED: 0
      SHOPWARE_ES_INDEXING_ENABLED: 0
      SHOPWARE_ES_INDEX_PREFIX: 
      COMPOSER_HOME: /tmp/composer
      SHOPWARE_HTTP_CACHE_ENABLED: 1
      SHOPWARE_HTTP_DEFAULT_TTL: 7200
      INSTALL_LOCALE: de-DE
      INSTALLED_SHOPWARE_VERSION: 6.2.0
    ports:
      - 8080:80
```
