### ISSUE TITLE
Smallest example not working for PHP version > 8.1.16 on Ubuntu server

### ISSUE THREAD

**Issue by ronnyworm** [shyim/shopware#82]
Error message from shopware container:

Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
...

I'm referring to this docker-compose example:

```
version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
  shopware:
    image: shyim/shopware:6.4.20-php8.2
    environment:
      APP_SECRET: 440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      INSTANCE_ID: 10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      APP_URL: http://localhost
      BLUE_GREEN_DEPLOYMENT: 0
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_URL: mysql://shopware:shopware@mysql:3306/shopware
    ports:
      - 80:80
```

When executed an M1 Mac, it works fine but on a brand new Ubuntu 22 server (lsb_release -a) ...
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

... it does not because for some reason PHP does not connect to the mysql-db. It works up to PHP 8.1.16 though e.g. with this image-tag: 6.4.20-php8.1.16 (8.1.17 does not)

I was running a basic `docker compose up`. At the end of everything where it should usually run, I'm getting constant '**Waiting for database connection...**' messages from the shopware container.

Please advise. For now I'm good with 6.4.20-php8.1.16
